# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "Sender Name"
    service:
        mailer:  fos_user.mailer.twig_swift
    resetting:
        email:
            from_email:
                address:        testmefos@gmail.com
                sender_name:    Demo Resetting

    registration:
        confirmation:
            enabled: true
            #template:   '@FOSUser/Registration/email.txt.twig'
