swiftmailer:
    transport:  "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:       "%mailer_host%"
    auth_mode:  "%mailer_auth_mode%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port: 465
    spool:     { type: memory }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
