<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TwhmRPL' shared service.

return $this->privates['.service_locator.TwhmRPL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'post' => array('privates', '.errored..service_locator.TwhmRPL.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.TwhmRPL": it references class "App\\Entity\\Post" but no such service exists.'),
));
