<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLXRF69C\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLXRF69C/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLXRF69C.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLXRF69C\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLXRF69C\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'LXRF69C',
    'container.build_id' => '237afcb1',
    'container.build_time' => 1544792470,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLXRF69C');
