<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIb56kgt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIb56kgt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIb56kgt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIb56kgt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIb56kgt\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Ib56kgt',
    'container.build_id' => '7e1d3526',
    'container.build_time' => 1544708205,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIb56kgt');
