<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oKrcl6Q' shared service.

return $this->privates['.service_locator.oKrcl6Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'comments' => array('privates', '.errored..service_locator.oKrcl6Q.App\\Entity\\Comments', NULL, 'Cannot autowire service ".service_locator.oKrcl6Q": it references class "App\\Entity\\Comments" but no such service exists.'),
));
